export const response = 
  {
  "total_count": 61,
  "incomplete_results": false,
  "items": [
    {
      "url": "https://api.github.com/repos/leanprover-community/lean/issues/44",
      "repository_url": "https://api.github.com/repos/leanprover-community/lean",
      "labels_url": "https://api.github.com/repos/leanprover-community/lean/issues/44/labels{/name}",
      "comments_url": "https://api.github.com/repos/leanprover-community/lean/issues/44/comments",
      "events_url": "https://api.github.com/repos/leanprover-community/lean/issues/44/events",
      "html_url": "https://github.com/leanprover-community/lean/pull/44",
      "id": 445669134,
      "node_id": "MDExOlB1bGxSZXF1ZXN0MjgwMDcxNjYw",
      "number": 44,
      "title": "Fix paths in ffi",
      "user": {
        "login": "agentultra",
        "id": 120574,
        "node_id": "MDQ6VXNlcjEyMDU3NA==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/120574?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/agentultra",
        "html_url": "https://github.com/agentultra",
        "followers_url": "https://api.github.com/users/agentultra/followers",
        "following_url": "https://api.github.com/users/agentultra/following{/other_user}",
        "gists_url": "https://api.github.com/users/agentultra/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/agentultra/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/agentultra/subscriptions",
        "organizations_url": "https://api.github.com/users/agentultra/orgs",
        "repos_url": "https://api.github.com/users/agentultra/repos",
        "events_url": "https://api.github.com/users/agentultra/events{/privacy}",
        "received_events_url": "https://api.github.com/users/agentultra/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2019-05-18T02:20:36Z",
      "updated_at": "2019-05-20T16:50:11Z",
      "closed_at": null,
      "author_association": "COLLABORATOR",
      "pull_request": {
        "url": "https://api.github.com/repos/leanprover-community/lean/pulls/44",
        "html_url": "https://github.com/leanprover-community/lean/pull/44",
        "diff_url": "https://github.com/leanprover-community/lean/pull/44.diff",
        "patch_url": "https://github.com/leanprover-community/lean/pull/44.patch"
      },
      "body": "",
      "score": 1
    },
    {
      "url": "https://api.github.com/repos/leanprover-community/lean/issues/42",
      "repository_url": "https://api.github.com/repos/leanprover-community/lean",
      "labels_url": "https://api.github.com/repos/leanprover-community/lean/issues/42/labels{/name}",
      "comments_url": "https://api.github.com/repos/leanprover-community/lean/issues/42/comments",
      "events_url": "https://api.github.com/repos/leanprover-community/lean/issues/42/events",
      "html_url": "https://github.com/leanprover-community/lean/pull/42",
      "id": 445237040,
      "node_id": "MDExOlB1bGxSZXF1ZXN0Mjc5NzMwMzkx",
      "number": 42,
      "title": "Upstream/vm dynload",
      "user": {
        "login": "agentultra",
        "id": 120574,
        "node_id": "MDQ6VXNlcjEyMDU3NA==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/120574?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/agentultra",
        "html_url": "https://github.com/agentultra",
        "followers_url": "https://api.github.com/users/agentultra/followers",
        "following_url": "https://api.github.com/users/agentultra/following{/other_user}",
        "gists_url": "https://api.github.com/users/agentultra/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/agentultra/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/agentultra/subscriptions",
        "organizations_url": "https://api.github.com/users/agentultra/orgs",
        "repos_url": "https://api.github.com/users/agentultra/repos",
        "events_url": "https://api.github.com/users/agentultra/events{/privacy}",
        "received_events_url": "https://api.github.com/users/agentultra/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [],
      "state": "closed",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2019-05-17T02:30:16Z",
      "updated_at": "2019-05-18T02:00:14Z",
      "closed_at": "2019-05-18T02:00:09Z",
      "author_association": "COLLABORATOR",
      "pull_request": {
        "url": "https://api.github.com/repos/leanprover-community/lean/pulls/42",
        "html_url": "https://github.com/leanprover-community/lean/pull/42",
        "diff_url": "https://github.com/leanprover-community/lean/pull/42.diff",
        "patch_url": "https://github.com/leanprover-community/lean/pull/42.patch"
      },
      "body": "Update some import paths to support linux",
      "score": 1
    },
    {
      "url": "https://api.github.com/repos/Codercamp/codercamp.github.io/issues/80",
      "repository_url": "https://api.github.com/repos/Codercamp/codercamp.github.io",
      "labels_url": "https://api.github.com/repos/Codercamp/codercamp.github.io/issues/80/labels{/name}",
      "comments_url": "https://api.github.com/repos/Codercamp/codercamp.github.io/issues/80/comments",
      "events_url": "https://api.github.com/repos/Codercamp/codercamp.github.io/issues/80/events",
      "html_url": "https://github.com/Codercamp/codercamp.github.io/pull/80",
      "id": 425096230,
      "node_id": "MDExOlB1bGxSZXF1ZXN0MjY0MjcyNDU5",
      "number": 80,
      "title": "Update 2019-04-10-CoderCamp-S19E04.md",
      "user": {
        "login": "agentultra",
        "id": 120574,
        "node_id": "MDQ6VXNlcjEyMDU3NA==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/120574?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/agentultra",
        "html_url": "https://github.com/agentultra",
        "followers_url": "https://api.github.com/users/agentultra/followers",
        "following_url": "https://api.github.com/users/agentultra/following{/other_user}",
        "gists_url": "https://api.github.com/users/agentultra/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/agentultra/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/agentultra/subscriptions",
        "organizations_url": "https://api.github.com/users/agentultra/orgs",
        "repos_url": "https://api.github.com/users/agentultra/repos",
        "events_url": "https://api.github.com/users/agentultra/events{/privacy}",
        "received_events_url": "https://api.github.com/users/agentultra/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [],
      "state": "closed",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2019-03-25T20:17:55Z",
      "updated_at": "2019-03-26T00:07:15Z",
      "closed_at": "2019-03-26T00:07:15Z",
      "author_association": "CONTRIBUTOR",
      "pull_request": {
        "url": "https://api.github.com/repos/Codercamp/codercamp.github.io/pulls/80",
        "html_url": "https://github.com/Codercamp/codercamp.github.io/pull/80",
        "diff_url": "https://github.com/Codercamp/codercamp.github.io/pull/80.diff",
        "patch_url": "https://github.com/Codercamp/codercamp.github.io/pull/80.patch"
      },
      "body": "Add a description for James' talk",
      "score": 1
    },
    {
      "url": "https://api.github.com/repos/agentultra/Checkr/issues/4",
      "repository_url": "https://api.github.com/repos/agentultra/Checkr",
      "labels_url": "https://api.github.com/repos/agentultra/Checkr/issues/4/labels{/name}",
      "comments_url": "https://api.github.com/repos/agentultra/Checkr/issues/4/comments",
      "events_url": "https://api.github.com/repos/agentultra/Checkr/issues/4/events",
      "html_url": "https://github.com/agentultra/Checkr/pull/4",
      "id": 382945770,
      "node_id": "MDExOlB1bGxSZXF1ZXN0MjMyNTMyMDA1",
      "number": 4,
      "title": "Modify src/Lib.hs",
      "user": {
        "login": "agentultra",
        "id": 120574,
        "node_id": "MDQ6VXNlcjEyMDU3NA==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/120574?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/agentultra",
        "html_url": "https://github.com/agentultra",
        "followers_url": "https://api.github.com/users/agentultra/followers",
        "following_url": "https://api.github.com/users/agentultra/following{/other_user}",
        "gists_url": "https://api.github.com/users/agentultra/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/agentultra/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/agentultra/subscriptions",
        "organizations_url": "https://api.github.com/users/agentultra/orgs",
        "repos_url": "https://api.github.com/users/agentultra/repos",
        "events_url": "https://api.github.com/users/agentultra/events{/privacy}",
        "received_events_url": "https://api.github.com/users/agentultra/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [],
      "state": "closed",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2018-11-21T04:00:20Z",
      "updated_at": "2018-11-21T04:07:26Z",
      "closed_at": "2018-11-21T04:07:23Z",
      "author_association": "OWNER",
      "pull_request": {
        "url": "https://api.github.com/repos/agentultra/Checkr/pulls/4",
        "html_url": "https://github.com/agentultra/Checkr/pull/4",
        "diff_url": "https://github.com/agentultra/Checkr/pull/4.diff",
        "patch_url": "https://github.com/agentultra/Checkr/pull/4.patch"
      },
      "body": "Removed `CreateUser` and replaced it with `PartialUser`.\r\n\r\nAlso added input validation to validate the name and email fields in\r\nthe POST handler for users.",
      "score": 1
    },
    {
      "url": "https://api.github.com/repos/agentultra/Checkr/issues/3",
      "repository_url": "https://api.github.com/repos/agentultra/Checkr",
      "labels_url": "https://api.github.com/repos/agentultra/Checkr/issues/3/labels{/name}",
      "comments_url": "https://api.github.com/repos/agentultra/Checkr/issues/3/comments",
      "events_url": "https://api.github.com/repos/agentultra/Checkr/issues/3/events",
      "html_url": "https://github.com/agentultra/Checkr/pull/3",
      "id": 382478795,
      "node_id": "MDExOlB1bGxSZXF1ZXN0MjMyMTc2OTUz",
      "number": 3,
      "title": "Modify src/Lib.hs",
      "user": {
        "login": "agentultra",
        "id": 120574,
        "node_id": "MDQ6VXNlcjEyMDU3NA==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/120574?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/agentultra",
        "html_url": "https://github.com/agentultra",
        "followers_url": "https://api.github.com/users/agentultra/followers",
        "following_url": "https://api.github.com/users/agentultra/following{/other_user}",
        "gists_url": "https://api.github.com/users/agentultra/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/agentultra/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/agentultra/subscriptions",
        "organizations_url": "https://api.github.com/users/agentultra/orgs",
        "repos_url": "https://api.github.com/users/agentultra/repos",
        "events_url": "https://api.github.com/users/agentultra/events{/privacy}",
        "received_events_url": "https://api.github.com/users/agentultra/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [],
      "state": "closed",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2018-11-20T02:57:42Z",
      "updated_at": "2018-11-20T02:57:57Z",
      "closed_at": "2018-11-20T02:57:54Z",
      "author_association": "OWNER",
      "pull_request": {
        "url": "https://api.github.com/repos/agentultra/Checkr/pulls/3",
        "html_url": "https://github.com/agentultra/Checkr/pull/3",
        "diff_url": "https://github.com/agentultra/Checkr/pull/3.diff",
        "patch_url": "https://github.com/agentultra/Checkr/pull/3.patch"
      },
      "body": "Add the concept of user states.\r\n\r\nA user state is one of _safe_, _at risk_, or _unknown_.\r\n\r\nBy default when we create a new user their state is _unknown_.\r\n\r\nParameterized the User type to give us the flexibility to lift the\r\nconcept of user states to the type level and create type aliases that\r\nallow us to define a SafeUser, AtRiskUser, etc.\r\n\r\nThe idea is to allow us to model the state transitions at the type\r\nlevel and use the type system to check our logic for us.",
      "score": 1
    },
    {
      "url": "https://api.github.com/repos/agentultra/Checkr/issues/2",
      "repository_url": "https://api.github.com/repos/agentultra/Checkr",
      "labels_url": "https://api.github.com/repos/agentultra/Checkr/issues/2/labels{/name}",
      "comments_url": "https://api.github.com/repos/agentultra/Checkr/issues/2/comments",
      "events_url": "https://api.github.com/repos/agentultra/Checkr/issues/2/events",
      "html_url": "https://github.com/agentultra/Checkr/pull/2",
      "id": 367269010,
      "node_id": "MDExOlB1bGxSZXF1ZXN0MjIwNzQ3MDAw",
      "number": 2,
      "title": "Modify src/Lib.hs",
      "user": {
        "login": "agentultra",
        "id": 120574,
        "node_id": "MDQ6VXNlcjEyMDU3NA==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/120574?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/agentultra",
        "html_url": "https://github.com/agentultra",
        "followers_url": "https://api.github.com/users/agentultra/followers",
        "following_url": "https://api.github.com/users/agentultra/following{/other_user}",
        "gists_url": "https://api.github.com/users/agentultra/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/agentultra/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/agentultra/subscriptions",
        "organizations_url": "https://api.github.com/users/agentultra/orgs",
        "repos_url": "https://api.github.com/users/agentultra/repos",
        "events_url": "https://api.github.com/users/agentultra/events{/privacy}",
        "received_events_url": "https://api.github.com/users/agentultra/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [],
      "state": "closed",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2018-10-05T15:49:29Z",
      "updated_at": "2018-10-05T15:49:46Z",
      "closed_at": "2018-10-05T15:49:43Z",
      "author_association": "OWNER",
      "pull_request": {
        "url": "https://api.github.com/repos/agentultra/Checkr/pulls/2",
        "html_url": "https://github.com/agentultra/Checkr/pull/2",
        "diff_url": "https://github.com/agentultra/Checkr/pull/2.diff",
        "patch_url": "https://github.com/agentultra/Checkr/pull/2.patch"
      },
      "body": "Added the MonadDB typeclass, created an instance, switched over `app`\r\nto use the typeclass interface.",
      "score": 1
    },
    {
      "url": "https://api.github.com/repos/agentultra/Checkr/issues/1",
      "repository_url": "https://api.github.com/repos/agentultra/Checkr",
      "labels_url": "https://api.github.com/repos/agentultra/Checkr/issues/1/labels{/name}",
      "comments_url": "https://api.github.com/repos/agentultra/Checkr/issues/1/comments",
      "events_url": "https://api.github.com/repos/agentultra/Checkr/issues/1/events",
      "html_url": "https://github.com/agentultra/Checkr/pull/1",
      "id": 366160681,
      "node_id": "MDExOlB1bGxSZXF1ZXN0MjE5OTA0Nzk0",
      "number": 1,
      "title": "Modify src/Lib.hs",
      "user": {
        "login": "agentultra",
        "id": 120574,
        "node_id": "MDQ6VXNlcjEyMDU3NA==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/120574?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/agentultra",
        "html_url": "https://github.com/agentultra",
        "followers_url": "https://api.github.com/users/agentultra/followers",
        "following_url": "https://api.github.com/users/agentultra/following{/other_user}",
        "gists_url": "https://api.github.com/users/agentultra/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/agentultra/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/agentultra/subscriptions",
        "organizations_url": "https://api.github.com/users/agentultra/orgs",
        "repos_url": "https://api.github.com/users/agentultra/repos",
        "events_url": "https://api.github.com/users/agentultra/events{/privacy}",
        "received_events_url": "https://api.github.com/users/agentultra/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [],
      "state": "closed",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2018-10-03T03:26:19Z",
      "updated_at": "2018-10-03T03:26:45Z",
      "closed_at": "2018-10-03T03:26:45Z",
      "author_association": "OWNER",
      "pull_request": {
        "url": "https://api.github.com/repos/agentultra/Checkr/pulls/1",
        "html_url": "https://github.com/agentultra/Checkr/pull/1",
        "diff_url": "https://github.com/agentultra/Checkr/pull/1.diff",
        "patch_url": "https://github.com/agentultra/Checkr/pull/1.patch"
      },
      "body": "Add a TVar to wrap our AppState and allow scotty action handlers to mutate it.\r\n\r\nAdded a post action handler to demonstrate how to add users in addition to reading the state.",
      "score": 1
    },
    {
      "url": "https://api.github.com/repos/agentultra/js13k2018/issues/2",
      "repository_url": "https://api.github.com/repos/agentultra/js13k2018",
      "labels_url": "https://api.github.com/repos/agentultra/js13k2018/issues/2/labels{/name}",
      "comments_url": "https://api.github.com/repos/agentultra/js13k2018/issues/2/comments",
      "events_url": "https://api.github.com/repos/agentultra/js13k2018/issues/2/events",
      "html_url": "https://github.com/agentultra/js13k2018/pull/2",
      "id": 356526003,
      "node_id": "MDExOlB1bGxSZXF1ZXN0MjEyNzY0NDU2",
      "number": 2,
      "title": "Add state management",
      "user": {
        "login": "agentultra",
        "id": 120574,
        "node_id": "MDQ6VXNlcjEyMDU3NA==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/120574?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/agentultra",
        "html_url": "https://github.com/agentultra",
        "followers_url": "https://api.github.com/users/agentultra/followers",
        "following_url": "https://api.github.com/users/agentultra/following{/other_user}",
        "gists_url": "https://api.github.com/users/agentultra/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/agentultra/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/agentultra/subscriptions",
        "organizations_url": "https://api.github.com/users/agentultra/orgs",
        "repos_url": "https://api.github.com/users/agentultra/repos",
        "events_url": "https://api.github.com/users/agentultra/events{/privacy}",
        "received_events_url": "https://api.github.com/users/agentultra/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [],
      "state": "closed",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2018-09-03T14:25:42Z",
      "updated_at": "2018-09-03T14:26:46Z",
      "closed_at": "2018-09-03T14:26:43Z",
      "author_association": "OWNER",
      "pull_request": {
        "url": "https://api.github.com/repos/agentultra/js13k2018/pulls/2",
        "html_url": "https://github.com/agentultra/js13k2018/pull/2",
        "diff_url": "https://github.com/agentultra/js13k2018/pull/2.diff",
        "patch_url": "https://github.com/agentultra/js13k2018/pull/2.patch"
      },
      "body": "",
      "score": 1
    },
    {
      "url": "https://api.github.com/repos/agentultra/js13k2018/issues/1",
      "repository_url": "https://api.github.com/repos/agentultra/js13k2018",
      "labels_url": "https://api.github.com/repos/agentultra/js13k2018/issues/1/labels{/name}",
      "comments_url": "https://api.github.com/repos/agentultra/js13k2018/issues/1/comments",
      "events_url": "https://api.github.com/repos/agentultra/js13k2018/issues/1/events",
      "html_url": "https://github.com/agentultra/js13k2018/pull/1",
      "id": 355802847,
      "node_id": "MDExOlB1bGxSZXF1ZXN0MjEyMjQ4MjI4",
      "number": 1,
      "title": "Tilemap",
      "user": {
        "login": "agentultra",
        "id": 120574,
        "node_id": "MDQ6VXNlcjEyMDU3NA==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/120574?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/agentultra",
        "html_url": "https://github.com/agentultra",
        "followers_url": "https://api.github.com/users/agentultra/followers",
        "following_url": "https://api.github.com/users/agentultra/following{/other_user}",
        "gists_url": "https://api.github.com/users/agentultra/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/agentultra/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/agentultra/subscriptions",
        "organizations_url": "https://api.github.com/users/agentultra/orgs",
        "repos_url": "https://api.github.com/users/agentultra/repos",
        "events_url": "https://api.github.com/users/agentultra/events{/privacy}",
        "received_events_url": "https://api.github.com/users/agentultra/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [],
      "state": "closed",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2018-08-31T00:53:00Z",
      "updated_at": "2018-08-31T00:53:15Z",
      "closed_at": "2018-08-31T00:53:12Z",
      "author_association": "OWNER",
      "pull_request": {
        "url": "https://api.github.com/repos/agentultra/js13k2018/pulls/1",
        "html_url": "https://github.com/agentultra/js13k2018/pull/1",
        "diff_url": "https://github.com/agentultra/js13k2018/pull/1.diff",
        "patch_url": "https://github.com/agentultra/js13k2018/pull/1.patch"
      },
      "body": "",
      "score": 1
    },
    {
      "url": "https://api.github.com/repos/flow-typed/flow-typed/issues/2137",
      "repository_url": "https://api.github.com/repos/flow-typed/flow-typed",
      "labels_url": "https://api.github.com/repos/flow-typed/flow-typed/issues/2137/labels{/name}",
      "comments_url": "https://api.github.com/repos/flow-typed/flow-typed/issues/2137/comments",
      "events_url": "https://api.github.com/repos/flow-typed/flow-typed/issues/2137/events",
      "html_url": "https://github.com/flow-typed/flow-typed/pull/2137",
      "id": 318245928,
      "node_id": "MDExOlB1bGxSZXF1ZXN0MTg0NTAxMzk2",
      "number": 2137,
      "title": "Update fantasy-options_v0.0.1/flow_v0.37.x",
      "user": {
        "login": "agentultra",
        "id": 120574,
        "node_id": "MDQ6VXNlcjEyMDU3NA==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/120574?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/agentultra",
        "html_url": "https://github.com/agentultra",
        "followers_url": "https://api.github.com/users/agentultra/followers",
        "following_url": "https://api.github.com/users/agentultra/following{/other_user}",
        "gists_url": "https://api.github.com/users/agentultra/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/agentultra/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/agentultra/subscriptions",
        "organizations_url": "https://api.github.com/users/agentultra/orgs",
        "repos_url": "https://api.github.com/users/agentultra/repos",
        "events_url": "https://api.github.com/users/agentultra/events{/privacy}",
        "received_events_url": "https://api.github.com/users/agentultra/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [],
      "state": "closed",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2018-04-27T01:11:28Z",
      "updated_at": "2018-07-03T19:10:35Z",
      "closed_at": "2018-04-28T02:41:10Z",
      "author_association": "CONTRIBUTOR",
      "pull_request": {
        "url": "https://api.github.com/repos/flow-typed/flow-typed/pulls/2137",
        "html_url": "https://github.com/flow-typed/flow-typed/pull/2137",
        "diff_url": "https://github.com/flow-typed/flow-typed/pull/2137.diff",
        "patch_url": "https://github.com/flow-typed/flow-typed/pull/2137.patch"
      },
      "body": "Changed the return types in `fold` to allow return types other than the value contained in the Option.\r\n\r\nThe fantasyland spec is unclear on `fold` and from practical use it seems more often than not we want some `f :: A -> B` as the parameter as opposed to the identity function.\r\n\r\nThe only restriction, to make fold safe to use, is that `f` and `g` have the _same_ return type.",
      "score": 1
    },
    {
      "url": "https://api.github.com/repos/Codercamp/codercamp.github.io/issues/70",
      "repository_url": "https://api.github.com/repos/Codercamp/codercamp.github.io",
      "labels_url": "https://api.github.com/repos/Codercamp/codercamp.github.io/issues/70/labels{/name}",
      "comments_url": "https://api.github.com/repos/Codercamp/codercamp.github.io/issues/70/comments",
      "events_url": "https://api.github.com/repos/Codercamp/codercamp.github.io/issues/70/events",
      "html_url": "https://github.com/Codercamp/codercamp.github.io/pull/70",
      "id": 302092555,
      "node_id": "MDExOlB1bGxSZXF1ZXN0MTcyNzIzNjk0",
      "number": 70,
      "title": "Update 2018-03-14-CoderCamp-S18E03.md",
      "user": {
        "login": "agentultra",
        "id": 120574,
        "node_id": "MDQ6VXNlcjEyMDU3NA==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/120574?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/agentultra",
        "html_url": "https://github.com/agentultra",
        "followers_url": "https://api.github.com/users/agentultra/followers",
        "following_url": "https://api.github.com/users/agentultra/following{/other_user}",
        "gists_url": "https://api.github.com/users/agentultra/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/agentultra/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/agentultra/subscriptions",
        "organizations_url": "https://api.github.com/users/agentultra/orgs",
        "repos_url": "https://api.github.com/users/agentultra/repos",
        "events_url": "https://api.github.com/users/agentultra/events{/privacy}",
        "received_events_url": "https://api.github.com/users/agentultra/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [],
      "state": "closed",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2018-03-04T15:02:51Z",
      "updated_at": "2018-03-04T15:10:12Z",
      "closed_at": "2018-03-04T15:10:12Z",
      "author_association": "CONTRIBUTOR",
      "pull_request": {
        "url": "https://api.github.com/repos/Codercamp/codercamp.github.io/pulls/70",
        "html_url": "https://github.com/Codercamp/codercamp.github.io/pull/70",
        "diff_url": "https://github.com/Codercamp/codercamp.github.io/pull/70.diff",
        "patch_url": "https://github.com/Codercamp/codercamp.github.io/pull/70.patch"
      },
      "body": "",
      "score": 1
    },
    {
      "url": "https://api.github.com/repos/JD95/haskell-problem-sets/issues/4",
      "repository_url": "https://api.github.com/repos/JD95/haskell-problem-sets",
      "labels_url": "https://api.github.com/repos/JD95/haskell-problem-sets/issues/4/labels{/name}",
      "comments_url": "https://api.github.com/repos/JD95/haskell-problem-sets/issues/4/comments",
      "events_url": "https://api.github.com/repos/JD95/haskell-problem-sets/issues/4/events",
      "html_url": "https://github.com/JD95/haskell-problem-sets/pull/4",
      "id": 290281677,
      "node_id": "MDExOlB1bGxSZXF1ZXN0MTY0MTgwNTk2",
      "number": 4,
      "title": "Update Lists/Tests.hs",
      "user": {
        "login": "agentultra",
        "id": 120574,
        "node_id": "MDQ6VXNlcjEyMDU3NA==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/120574?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/agentultra",
        "html_url": "https://github.com/agentultra",
        "followers_url": "https://api.github.com/users/agentultra/followers",
        "following_url": "https://api.github.com/users/agentultra/following{/other_user}",
        "gists_url": "https://api.github.com/users/agentultra/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/agentultra/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/agentultra/subscriptions",
        "organizations_url": "https://api.github.com/users/agentultra/orgs",
        "repos_url": "https://api.github.com/users/agentultra/repos",
        "events_url": "https://api.github.com/users/agentultra/events{/privacy}",
        "received_events_url": "https://api.github.com/users/agentultra/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [],
      "state": "closed",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2018-01-21T15:37:25Z",
      "updated_at": "2018-01-21T15:39:23Z",
      "closed_at": "2018-01-21T15:39:23Z",
      "author_association": "CONTRIBUTOR",
      "pull_request": {
        "url": "https://api.github.com/repos/JD95/haskell-problem-sets/pulls/4",
        "html_url": "https://github.com/JD95/haskell-problem-sets/pull/4",
        "diff_url": "https://github.com/JD95/haskell-problem-sets/pull/4.diff",
        "patch_url": "https://github.com/JD95/haskell-problem-sets/pull/4.patch"
      },
      "body": "I changed the imports and function names to avoid clashing with Prelude.\r\n\r\nI also added missing test cases for some of the list functions.",
      "score": 1
    },
    {
      "url": "https://api.github.com/repos/JD95/haskell-problem-sets/issues/3",
      "repository_url": "https://api.github.com/repos/JD95/haskell-problem-sets",
      "labels_url": "https://api.github.com/repos/JD95/haskell-problem-sets/issues/3/labels{/name}",
      "comments_url": "https://api.github.com/repos/JD95/haskell-problem-sets/issues/3/comments",
      "events_url": "https://api.github.com/repos/JD95/haskell-problem-sets/issues/3/events",
      "html_url": "https://github.com/JD95/haskell-problem-sets/pull/3",
      "id": 286491726,
      "node_id": "MDExOlB1bGxSZXF1ZXN0MTYxNDgzOTY2",
      "number": 3,
      "title": "Update Arithmetic/Tests.hs",
      "user": {
        "login": "agentultra",
        "id": 120574,
        "node_id": "MDQ6VXNlcjEyMDU3NA==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/120574?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/agentultra",
        "html_url": "https://github.com/agentultra",
        "followers_url": "https://api.github.com/users/agentultra/followers",
        "following_url": "https://api.github.com/users/agentultra/following{/other_user}",
        "gists_url": "https://api.github.com/users/agentultra/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/agentultra/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/agentultra/subscriptions",
        "organizations_url": "https://api.github.com/users/agentultra/orgs",
        "repos_url": "https://api.github.com/users/agentultra/repos",
        "events_url": "https://api.github.com/users/agentultra/events{/privacy}",
        "received_events_url": "https://api.github.com/users/agentultra/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [],
      "state": "closed",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2018-01-06T15:31:02Z",
      "updated_at": "2018-01-06T23:35:16Z",
      "closed_at": "2018-01-06T23:35:16Z",
      "author_association": "CONTRIBUTOR",
      "pull_request": {
        "url": "https://api.github.com/repos/JD95/haskell-problem-sets/pulls/3",
        "html_url": "https://github.com/JD95/haskell-problem-sets/pull/3",
        "diff_url": "https://github.com/JD95/haskell-problem-sets/pull/3.diff",
        "patch_url": "https://github.com/JD95/haskell-problem-sets/pull/3.patch"
      },
      "body": "This test imports the Problems module here qualified to avoid ambiguous\r\nreferences with Prelude.\r\n\r\nAlso caught a small typo in Problems.hs",
      "score": 1
    },
    {
      "url": "https://api.github.com/repos/agentultra/Advent2017/issues/1",
      "repository_url": "https://api.github.com/repos/agentultra/Advent2017",
      "labels_url": "https://api.github.com/repos/agentultra/Advent2017/issues/1/labels{/name}",
      "comments_url": "https://api.github.com/repos/agentultra/Advent2017/issues/1/comments",
      "events_url": "https://api.github.com/repos/agentultra/Advent2017/issues/1/events",
      "html_url": "https://github.com/agentultra/Advent2017/pull/1",
      "id": 283440142,
      "node_id": "MDExOlB1bGxSZXF1ZXN0MTU5MzI0NjMw",
      "number": 1,
      "title": "Add DaySeven",
      "user": {
        "login": "agentultra",
        "id": 120574,
        "node_id": "MDQ6VXNlcjEyMDU3NA==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/120574?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/agentultra",
        "html_url": "https://github.com/agentultra",
        "followers_url": "https://api.github.com/users/agentultra/followers",
        "following_url": "https://api.github.com/users/agentultra/following{/other_user}",
        "gists_url": "https://api.github.com/users/agentultra/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/agentultra/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/agentultra/subscriptions",
        "organizations_url": "https://api.github.com/users/agentultra/orgs",
        "repos_url": "https://api.github.com/users/agentultra/repos",
        "events_url": "https://api.github.com/users/agentultra/events{/privacy}",
        "received_events_url": "https://api.github.com/users/agentultra/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [],
      "state": "closed",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2017-12-20T03:39:14Z",
      "updated_at": "2017-12-20T03:39:33Z",
      "closed_at": "2017-12-20T03:39:30Z",
      "author_association": "OWNER",
      "pull_request": {
        "url": "https://api.github.com/repos/agentultra/Advent2017/pulls/1",
        "html_url": "https://github.com/agentultra/Advent2017/pull/1",
        "diff_url": "https://github.com/agentultra/Advent2017/pull/1.diff",
        "patch_url": "https://github.com/agentultra/Advent2017/pull/1.patch"
      },
      "body": "",
      "score": 1
    },
    {
      "url": "https://api.github.com/repos/Codercamp/codercamp.github.io/issues/65",
      "repository_url": "https://api.github.com/repos/Codercamp/codercamp.github.io",
      "labels_url": "https://api.github.com/repos/Codercamp/codercamp.github.io/issues/65/labels{/name}",
      "comments_url": "https://api.github.com/repos/Codercamp/codercamp.github.io/issues/65/comments",
      "events_url": "https://api.github.com/repos/Codercamp/codercamp.github.io/issues/65/events",
      "html_url": "https://github.com/Codercamp/codercamp.github.io/pull/65",
      "id": 256752101,
      "node_id": "MDExOlB1bGxSZXF1ZXN0MTQwMzY5OTE4",
      "number": 65,
      "title": "Update 2017-10-11-CoderCamp-S17E10.md",
      "user": {
        "login": "agentultra",
        "id": 120574,
        "node_id": "MDQ6VXNlcjEyMDU3NA==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/120574?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/agentultra",
        "html_url": "https://github.com/agentultra",
        "followers_url": "https://api.github.com/users/agentultra/followers",
        "following_url": "https://api.github.com/users/agentultra/following{/other_user}",
        "gists_url": "https://api.github.com/users/agentultra/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/agentultra/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/agentultra/subscriptions",
        "organizations_url": "https://api.github.com/users/agentultra/orgs",
        "repos_url": "https://api.github.com/users/agentultra/repos",
        "events_url": "https://api.github.com/users/agentultra/events{/privacy}",
        "received_events_url": "https://api.github.com/users/agentultra/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [],
      "state": "closed",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2017-09-11T15:50:58Z",
      "updated_at": "2017-09-11T16:03:19Z",
      "closed_at": "2017-09-11T16:03:19Z",
      "author_association": "CONTRIBUTOR",
      "pull_request": {
        "url": "https://api.github.com/repos/Codercamp/codercamp.github.io/pulls/65",
        "html_url": "https://github.com/Codercamp/codercamp.github.io/pull/65",
        "diff_url": "https://github.com/Codercamp/codercamp.github.io/pull/65.diff",
        "patch_url": "https://github.com/Codercamp/codercamp.github.io/pull/65.patch"
      },
      "body": "Add my proposal for a 5-minute talk on how to abuse JS where code-size is your limitation.",
      "score": 1
    },
    {
      "url": "https://api.github.com/repos/Codercamp/codercamp.github.io/issues/62",
      "repository_url": "https://api.github.com/repos/Codercamp/codercamp.github.io",
      "labels_url": "https://api.github.com/repos/Codercamp/codercamp.github.io/issues/62/labels{/name}",
      "comments_url": "https://api.github.com/repos/Codercamp/codercamp.github.io/issues/62/comments",
      "events_url": "https://api.github.com/repos/Codercamp/codercamp.github.io/issues/62/events",
      "html_url": "https://github.com/Codercamp/codercamp.github.io/pull/62",
      "id": 226813873,
      "node_id": "MDExOlB1bGxSZXF1ZXN0MTE5MzIwNTMw",
      "number": 62,
      "title": "Update 2017-05-10-CoderCamp-S17E05.md",
      "user": {
        "login": "agentultra",
        "id": 120574,
        "node_id": "MDQ6VXNlcjEyMDU3NA==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/120574?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/agentultra",
        "html_url": "https://github.com/agentultra",
        "followers_url": "https://api.github.com/users/agentultra/followers",
        "following_url": "https://api.github.com/users/agentultra/following{/other_user}",
        "gists_url": "https://api.github.com/users/agentultra/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/agentultra/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/agentultra/subscriptions",
        "organizations_url": "https://api.github.com/users/agentultra/orgs",
        "repos_url": "https://api.github.com/users/agentultra/repos",
        "events_url": "https://api.github.com/users/agentultra/events{/privacy}",
        "received_events_url": "https://api.github.com/users/agentultra/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [],
      "state": "closed",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2017-05-06T23:56:26Z",
      "updated_at": "2017-05-07T00:57:33Z",
      "closed_at": "2017-05-07T00:57:33Z",
      "author_association": "CONTRIBUTOR",
      "pull_request": {
        "url": "https://api.github.com/repos/Codercamp/codercamp.github.io/pulls/62",
        "html_url": "https://github.com/Codercamp/codercamp.github.io/pull/62",
        "diff_url": "https://github.com/Codercamp/codercamp.github.io/pull/62.diff",
        "patch_url": "https://github.com/Codercamp/codercamp.github.io/pull/62.patch"
      },
      "body": "Set the title of the talk and description",
      "score": 1
    },
    {
      "url": "https://api.github.com/repos/flow-typed/flow-typed/issues/793",
      "repository_url": "https://api.github.com/repos/flow-typed/flow-typed",
      "labels_url": "https://api.github.com/repos/flow-typed/flow-typed/issues/793/labels{/name}",
      "comments_url": "https://api.github.com/repos/flow-typed/flow-typed/issues/793/comments",
      "events_url": "https://api.github.com/repos/flow-typed/flow-typed/issues/793/events",
      "html_url": "https://github.com/flow-typed/flow-typed/pull/793",
      "id": 223389841,
      "node_id": "MDExOlB1bGxSZXF1ZXN0MTE2OTg5ODE0",
      "number": 793,
      "title": "Add fantasy-options definition",
      "user": {
        "login": "agentultra",
        "id": 120574,
        "node_id": "MDQ6VXNlcjEyMDU3NA==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/120574?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/agentultra",
        "html_url": "https://github.com/agentultra",
        "followers_url": "https://api.github.com/users/agentultra/followers",
        "following_url": "https://api.github.com/users/agentultra/following{/other_user}",
        "gists_url": "https://api.github.com/users/agentultra/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/agentultra/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/agentultra/subscriptions",
        "organizations_url": "https://api.github.com/users/agentultra/orgs",
        "repos_url": "https://api.github.com/users/agentultra/repos",
        "events_url": "https://api.github.com/users/agentultra/events{/privacy}",
        "received_events_url": "https://api.github.com/users/agentultra/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [],
      "state": "closed",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2017-04-21T13:51:28Z",
      "updated_at": "2018-07-03T19:09:23Z",
      "closed_at": "2017-05-12T20:43:15Z",
      "author_association": "CONTRIBUTOR",
      "pull_request": {
        "url": "https://api.github.com/repos/flow-typed/flow-typed/pulls/793",
        "html_url": "https://github.com/flow-typed/flow-typed/pull/793",
        "diff_url": "https://github.com/flow-typed/flow-typed/pull/793.diff",
        "patch_url": "https://github.com/flow-typed/flow-typed/pull/793.patch"
      },
      "body": "There are a couple of test cases that I think should cause errors (they do at runtime) but fail to type check. They are noted in the test file with comments.\r\n\r\nI'm not sure how to solve those right now, help would be appreciated.",
      "score": 1
    },
    {
      "url": "https://api.github.com/repos/Codercamp/codercamp.github.io/issues/61",
      "repository_url": "https://api.github.com/repos/Codercamp/codercamp.github.io",
      "labels_url": "https://api.github.com/repos/Codercamp/codercamp.github.io/issues/61/labels{/name}",
      "comments_url": "https://api.github.com/repos/Codercamp/codercamp.github.io/issues/61/comments",
      "events_url": "https://api.github.com/repos/Codercamp/codercamp.github.io/issues/61/events",
      "html_url": "https://github.com/Codercamp/codercamp.github.io/pull/61",
      "id": 223108815,
      "node_id": "MDExOlB1bGxSZXF1ZXN0MTE2ODAwOTM3",
      "number": 61,
      "title": "Create 2017-05-10-CoderCamp-S17E05.md",
      "user": {
        "login": "agentultra",
        "id": 120574,
        "node_id": "MDQ6VXNlcjEyMDU3NA==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/120574?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/agentultra",
        "html_url": "https://github.com/agentultra",
        "followers_url": "https://api.github.com/users/agentultra/followers",
        "following_url": "https://api.github.com/users/agentultra/following{/other_user}",
        "gists_url": "https://api.github.com/users/agentultra/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/agentultra/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/agentultra/subscriptions",
        "organizations_url": "https://api.github.com/users/agentultra/orgs",
        "repos_url": "https://api.github.com/users/agentultra/repos",
        "events_url": "https://api.github.com/users/agentultra/events{/privacy}",
        "received_events_url": "https://api.github.com/users/agentultra/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [],
      "state": "closed",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 3,
      "created_at": "2017-04-20T15:34:09Z",
      "updated_at": "2017-04-20T16:42:36Z",
      "closed_at": "2017-04-20T15:55:18Z",
      "author_association": "CONTRIBUTOR",
      "pull_request": {
        "url": "https://api.github.com/repos/Codercamp/codercamp.github.io/pulls/61",
        "html_url": "https://github.com/Codercamp/codercamp.github.io/pull/61",
        "diff_url": "https://github.com/Codercamp/codercamp.github.io/pull/61.diff",
        "patch_url": "https://github.com/Codercamp/codercamp.github.io/pull/61.patch"
      },
      "body": "Adds a slot for my TBD talk next month...",
      "score": 1
    },
    {
      "url": "https://api.github.com/repos/ramda/ramda/issues/2112",
      "repository_url": "https://api.github.com/repos/ramda/ramda",
      "labels_url": "https://api.github.com/repos/ramda/ramda/issues/2112/labels{/name}",
      "comments_url": "https://api.github.com/repos/ramda/ramda/issues/2112/comments",
      "events_url": "https://api.github.com/repos/ramda/ramda/issues/2112/events",
      "html_url": "https://github.com/ramda/ramda/pull/2112",
      "id": 211851713,
      "node_id": "MDExOlB1bGxSZXF1ZXN0MTA5MDkxNzQ1",
      "number": 2112,
      "title": "Add through function",
      "user": {
        "login": "agentultra",
        "id": 120574,
        "node_id": "MDQ6VXNlcjEyMDU3NA==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/120574?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/agentultra",
        "html_url": "https://github.com/agentultra",
        "followers_url": "https://api.github.com/users/agentultra/followers",
        "following_url": "https://api.github.com/users/agentultra/following{/other_user}",
        "gists_url": "https://api.github.com/users/agentultra/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/agentultra/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/agentultra/subscriptions",
        "organizations_url": "https://api.github.com/users/agentultra/orgs",
        "repos_url": "https://api.github.com/users/agentultra/repos",
        "events_url": "https://api.github.com/users/agentultra/events{/privacy}",
        "received_events_url": "https://api.github.com/users/agentultra/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [],
      "state": "closed",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 4,
      "created_at": "2017-03-04T03:36:26Z",
      "updated_at": "2017-11-23T14:37:15Z",
      "closed_at": "2017-11-23T14:37:08Z",
      "author_association": "NONE",
      "pull_request": {
        "url": "https://api.github.com/repos/ramda/ramda/pulls/2112",
        "html_url": "https://github.com/ramda/ramda/pull/2112",
        "diff_url": "https://github.com/ramda/ramda/pull/2112.diff",
        "patch_url": "https://github.com/ramda/ramda/pull/2112.patch"
      },
      "body": "This function takes a list of getter functions and an object. It returns\r\nthe first non-nil value from the list of getters. It returns null if\r\nnothing is found.",
      "score": 1
    },
    {
      "url": "https://api.github.com/repos/aio-libs/aiocouchdb/issues/16",
      "repository_url": "https://api.github.com/repos/aio-libs/aiocouchdb",
      "labels_url": "https://api.github.com/repos/aio-libs/aiocouchdb/issues/16/labels{/name}",
      "comments_url": "https://api.github.com/repos/aio-libs/aiocouchdb/issues/16/comments",
      "events_url": "https://api.github.com/repos/aio-libs/aiocouchdb/issues/16/events",
      "html_url": "https://github.com/aio-libs/aiocouchdb/pull/16",
      "id": 172525498,
      "node_id": "MDExOlB1bGxSZXF1ZXN0ODIyNDIzMDE=",
      "number": 16,
      "title": "Update aiohttp dependency",
      "user": {
        "login": "agentultra",
        "id": 120574,
        "node_id": "MDQ6VXNlcjEyMDU3NA==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/120574?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/agentultra",
        "html_url": "https://github.com/agentultra",
        "followers_url": "https://api.github.com/users/agentultra/followers",
        "following_url": "https://api.github.com/users/agentultra/following{/other_user}",
        "gists_url": "https://api.github.com/users/agentultra/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/agentultra/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/agentultra/subscriptions",
        "organizations_url": "https://api.github.com/users/agentultra/orgs",
        "repos_url": "https://api.github.com/users/agentultra/repos",
        "events_url": "https://api.github.com/users/agentultra/events{/privacy}",
        "received_events_url": "https://api.github.com/users/agentultra/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 5,
      "created_at": "2016-08-22T18:47:17Z",
      "updated_at": "2017-05-18T03:57:30Z",
      "closed_at": null,
      "author_association": "NONE",
      "pull_request": {
        "url": "https://api.github.com/repos/aio-libs/aiocouchdb/pulls/16",
        "html_url": "https://github.com/aio-libs/aiocouchdb/pull/16",
        "diff_url": "https://github.com/aio-libs/aiocouchdb/pull/16.diff",
        "patch_url": "https://github.com/aio-libs/aiocouchdb/pull/16.patch"
      },
      "body": "This change updates aiohttp to >= 0.22.1 and updates the code to the new\nAPIs.\n",
      "score": 1
    },
    {
      "url": "https://api.github.com/repos/github/linguist/issues/2981",
      "repository_url": "https://api.github.com/repos/github/linguist",
      "labels_url": "https://api.github.com/repos/github/linguist/issues/2981/labels{/name}",
      "comments_url": "https://api.github.com/repos/github/linguist/issues/2981/comments",
      "events_url": "https://api.github.com/repos/github/linguist/issues/2981/events",
      "html_url": "https://github.com/github/linguist/pull/2981",
      "id": 152908881,
      "node_id": "MDExOlB1bGxSZXF1ZXN0Njg3OTkxNTQ=",
      "number": 2981,
      "title": "Add support for TLA+",
      "user": {
        "login": "agentultra",
        "id": 120574,
        "node_id": "MDQ6VXNlcjEyMDU3NA==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/120574?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/agentultra",
        "html_url": "https://github.com/agentultra",
        "followers_url": "https://api.github.com/users/agentultra/followers",
        "following_url": "https://api.github.com/users/agentultra/following{/other_user}",
        "gists_url": "https://api.github.com/users/agentultra/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/agentultra/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/agentultra/subscriptions",
        "organizations_url": "https://api.github.com/users/agentultra/orgs",
        "repos_url": "https://api.github.com/users/agentultra/repos",
        "events_url": "https://api.github.com/users/agentultra/events{/privacy}",
        "received_events_url": "https://api.github.com/users/agentultra/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [],
      "state": "closed",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 1,
      "created_at": "2016-05-04T01:08:55Z",
      "updated_at": "2016-05-06T19:16:50Z",
      "closed_at": "2016-05-06T19:16:50Z",
      "author_association": "NONE",
      "pull_request": {
        "url": "https://api.github.com/repos/github/linguist/pulls/2981",
        "html_url": "https://github.com/github/linguist/pull/2981",
        "diff_url": "https://github.com/github/linguist/pull/2981.diff",
        "patch_url": "https://github.com/github/linguist/pull/2981.patch"
      },
      "body": "This patch adds support for the TLA+ specification language.\n\nhttps://github.com/search?utf8=%E2%9C%93&q=MODULE+extension%3Atla&type=Code&ref=searchresults\n",
      "score": 1
    },
    {
      "url": "https://api.github.com/repos/traverseda/pycraft/issues/41",
      "repository_url": "https://api.github.com/repos/traverseda/pycraft",
      "labels_url": "https://api.github.com/repos/traverseda/pycraft/issues/41/labels{/name}",
      "comments_url": "https://api.github.com/repos/traverseda/pycraft/issues/41/comments",
      "events_url": "https://api.github.com/repos/traverseda/pycraft/issues/41/events",
      "html_url": "https://github.com/traverseda/pycraft/pull/41",
      "id": 149624155,
      "node_id": "MDExOlB1bGxSZXF1ZXN0NjcxMTQzNDc=",
      "number": 41,
      "title": "Add WeakStone",
      "user": {
        "login": "agentultra",
        "id": 120574,
        "node_id": "MDQ6VXNlcjEyMDU3NA==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/120574?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/agentultra",
        "html_url": "https://github.com/agentultra",
        "followers_url": "https://api.github.com/users/agentultra/followers",
        "following_url": "https://api.github.com/users/agentultra/following{/other_user}",
        "gists_url": "https://api.github.com/users/agentultra/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/agentultra/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/agentultra/subscriptions",
        "organizations_url": "https://api.github.com/users/agentultra/orgs",
        "repos_url": "https://api.github.com/users/agentultra/repos",
        "events_url": "https://api.github.com/users/agentultra/events{/privacy}",
        "received_events_url": "https://api.github.com/users/agentultra/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [],
      "state": "closed",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 2,
      "created_at": "2016-04-20T01:04:06Z",
      "updated_at": "2016-04-20T01:07:12Z",
      "closed_at": "2016-04-20T01:07:11Z",
      "author_association": "CONTRIBUTOR",
      "pull_request": {
        "url": "https://api.github.com/repos/traverseda/pycraft/pulls/41",
        "html_url": "https://github.com/traverseda/pycraft/pull/41",
        "diff_url": "https://github.com/traverseda/pycraft/pull/41.diff",
        "patch_url": "https://github.com/traverseda/pycraft/pull/41.patch"
      },
      "body": "A minor patch to add a breakable stone type which makes way for a\n'breakable' attribute on blocks.\n",
      "score": 1
    },
    {
      "url": "https://api.github.com/repos/GrappigPanda/pygemony/issues/144",
      "repository_url": "https://api.github.com/repos/GrappigPanda/pygemony",
      "labels_url": "https://api.github.com/repos/GrappigPanda/pygemony/issues/144/labels{/name}",
      "comments_url": "https://api.github.com/repos/GrappigPanda/pygemony/issues/144/comments",
      "events_url": "https://api.github.com/repos/GrappigPanda/pygemony/issues/144/events",
      "html_url": "https://github.com/GrappigPanda/pygemony/pull/144",
      "id": 136800753,
      "node_id": "MDExOlB1bGxSZXF1ZXN0NjA4OTYzMTQ=",
      "number": 144,
      "title": "Add some basic py3.5-compatibility",
      "user": {
        "login": "agentultra",
        "id": 120574,
        "node_id": "MDQ6VXNlcjEyMDU3NA==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/120574?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/agentultra",
        "html_url": "https://github.com/agentultra",
        "followers_url": "https://api.github.com/users/agentultra/followers",
        "following_url": "https://api.github.com/users/agentultra/following{/other_user}",
        "gists_url": "https://api.github.com/users/agentultra/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/agentultra/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/agentultra/subscriptions",
        "organizations_url": "https://api.github.com/users/agentultra/orgs",
        "repos_url": "https://api.github.com/users/agentultra/repos",
        "events_url": "https://api.github.com/users/agentultra/events{/privacy}",
        "received_events_url": "https://api.github.com/users/agentultra/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [],
      "state": "closed",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 3,
      "created_at": "2016-02-26T20:07:15Z",
      "updated_at": "2016-02-26T20:13:17Z",
      "closed_at": "2016-02-26T20:08:17Z",
      "author_association": "NONE",
      "pull_request": {
        "url": "https://api.github.com/repos/GrappigPanda/pygemony/pulls/144",
        "html_url": "https://github.com/GrappigPanda/pygemony/pull/144",
        "diff_url": "https://github.com/GrappigPanda/pygemony/pull/144.diff",
        "patch_url": "https://github.com/GrappigPanda/pygemony/pull/144.patch"
      },
      "body": "",
      "score": 1
    },
    {
      "url": "https://api.github.com/repos/GrappigPanda/pygemony/issues/143",
      "repository_url": "https://api.github.com/repos/GrappigPanda/pygemony",
      "labels_url": "https://api.github.com/repos/GrappigPanda/pygemony/issues/143/labels{/name}",
      "comments_url": "https://api.github.com/repos/GrappigPanda/pygemony/issues/143/comments",
      "events_url": "https://api.github.com/repos/GrappigPanda/pygemony/issues/143/events",
      "html_url": "https://github.com/GrappigPanda/pygemony/pull/143",
      "id": 136798286,
      "node_id": "MDExOlB1bGxSZXF1ZXN0NjA4OTQ5MzY=",
      "number": 143,
      "title": "Add some basic py3.5-compatibility",
      "user": {
        "login": "agentultra",
        "id": 120574,
        "node_id": "MDQ6VXNlcjEyMDU3NA==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/120574?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/agentultra",
        "html_url": "https://github.com/agentultra",
        "followers_url": "https://api.github.com/users/agentultra/followers",
        "following_url": "https://api.github.com/users/agentultra/following{/other_user}",
        "gists_url": "https://api.github.com/users/agentultra/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/agentultra/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/agentultra/subscriptions",
        "organizations_url": "https://api.github.com/users/agentultra/orgs",
        "repos_url": "https://api.github.com/users/agentultra/repos",
        "events_url": "https://api.github.com/users/agentultra/events{/privacy}",
        "received_events_url": "https://api.github.com/users/agentultra/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [],
      "state": "closed",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 2,
      "created_at": "2016-02-26T19:57:33Z",
      "updated_at": "2016-02-26T20:06:35Z",
      "closed_at": "2016-02-26T20:06:35Z",
      "author_association": "NONE",
      "pull_request": {
        "url": "https://api.github.com/repos/GrappigPanda/pygemony/pulls/143",
        "html_url": "https://github.com/GrappigPanda/pygemony/pull/143",
        "diff_url": "https://github.com/GrappigPanda/pygemony/pull/143.diff",
        "patch_url": "https://github.com/GrappigPanda/pygemony/pull/143.patch"
      },
      "body": "This is just a basic patch to get the test to pass under Python 3.5 and isn't a full-fledged solution to supporting Python 2/3 in the future.\n\nI'd recommend adding six as a dependency in a future patch.\n",
      "score": 1
    },
    {
      "url": "https://api.github.com/repos/dreamhost/akanda-devstack/issues/26",
      "repository_url": "https://api.github.com/repos/dreamhost/akanda-devstack",
      "labels_url": "https://api.github.com/repos/dreamhost/akanda-devstack/issues/26/labels{/name}",
      "comments_url": "https://api.github.com/repos/dreamhost/akanda-devstack/issues/26/comments",
      "events_url": "https://api.github.com/repos/dreamhost/akanda-devstack/issues/26/events",
      "html_url": "https://github.com/dreamhost/akanda-devstack/pull/26",
      "id": 59141019,
      "node_id": "MDExOlB1bGxSZXF1ZXN0MzAxMTQ4MDI=",
      "number": 26,
      "title": "Update pre_start_akanda",
      "user": {
        "login": "agentultra",
        "id": 120574,
        "node_id": "MDQ6VXNlcjEyMDU3NA==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/120574?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/agentultra",
        "html_url": "https://github.com/agentultra",
        "followers_url": "https://api.github.com/users/agentultra/followers",
        "following_url": "https://api.github.com/users/agentultra/following{/other_user}",
        "gists_url": "https://api.github.com/users/agentultra/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/agentultra/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/agentultra/subscriptions",
        "organizations_url": "https://api.github.com/users/agentultra/orgs",
        "repos_url": "https://api.github.com/users/agentultra/repos",
        "events_url": "https://api.github.com/users/agentultra/events{/privacy}",
        "received_events_url": "https://api.github.com/users/agentultra/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [],
      "state": "closed",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2015-02-26T20:49:06Z",
      "updated_at": "2015-02-27T15:26:39Z",
      "closed_at": "2015-02-27T15:26:39Z",
      "author_association": "CONTRIBUTOR",
      "pull_request": {
        "url": "https://api.github.com/repos/dreamhost/akanda-devstack/pulls/26",
        "html_url": "https://github.com/dreamhost/akanda-devstack/pull/26",
        "diff_url": "https://github.com/dreamhost/akanda-devstack/pull/26.diff",
        "patch_url": "https://github.com/dreamhost/akanda-devstack/pull/26.patch"
      },
      "body": "Just fixes up the CLI args to match juno\n",
      "score": 1
    },
    {
      "url": "https://api.github.com/repos/dreamhost/akanda-devstack/issues/17",
      "repository_url": "https://api.github.com/repos/dreamhost/akanda-devstack",
      "labels_url": "https://api.github.com/repos/dreamhost/akanda-devstack/issues/17/labels{/name}",
      "comments_url": "https://api.github.com/repos/dreamhost/akanda-devstack/issues/17/comments",
      "events_url": "https://api.github.com/repos/dreamhost/akanda-devstack/issues/17/events",
      "html_url": "https://github.com/dreamhost/akanda-devstack/pull/17",
      "id": 57657737,
      "node_id": "MDExOlB1bGxSZXF1ZXN0MjkzMDE1MDA=",
      "number": 17,
      "title": "unstack ak-rug",
      "user": {
        "login": "agentultra",
        "id": 120574,
        "node_id": "MDQ6VXNlcjEyMDU3NA==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/120574?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/agentultra",
        "html_url": "https://github.com/agentultra",
        "followers_url": "https://api.github.com/users/agentultra/followers",
        "following_url": "https://api.github.com/users/agentultra/following{/other_user}",
        "gists_url": "https://api.github.com/users/agentultra/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/agentultra/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/agentultra/subscriptions",
        "organizations_url": "https://api.github.com/users/agentultra/orgs",
        "repos_url": "https://api.github.com/users/agentultra/repos",
        "events_url": "https://api.github.com/users/agentultra/events{/privacy}",
        "received_events_url": "https://api.github.com/users/agentultra/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [],
      "state": "closed",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2015-02-13T21:40:52Z",
      "updated_at": "2015-02-13T21:43:44Z",
      "closed_at": "2015-02-13T21:43:44Z",
      "author_association": "CONTRIBUTOR",
      "pull_request": {
        "url": "https://api.github.com/repos/dreamhost/akanda-devstack/pulls/17",
        "html_url": "https://github.com/dreamhost/akanda-devstack/pull/17",
        "diff_url": "https://github.com/dreamhost/akanda-devstack/pull/17.diff",
        "patch_url": "https://github.com/dreamhost/akanda-devstack/pull/17.patch"
      },
      "body": "",
      "score": 1
    },
    {
      "url": "https://api.github.com/repos/agentultra/dmon/issues/7",
      "repository_url": "https://api.github.com/repos/agentultra/dmon",
      "labels_url": "https://api.github.com/repos/agentultra/dmon/issues/7/labels{/name}",
      "comments_url": "https://api.github.com/repos/agentultra/dmon/issues/7/comments",
      "events_url": "https://api.github.com/repos/agentultra/dmon/issues/7/events",
      "html_url": "https://github.com/agentultra/dmon/pull/7",
      "id": 56865737,
      "node_id": "MDExOlB1bGxSZXF1ZXN0Mjg4NDA2NDE=",
      "number": 7,
      "title": "Add Hy support",
      "user": {
        "login": "agentultra",
        "id": 120574,
        "node_id": "MDQ6VXNlcjEyMDU3NA==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/120574?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/agentultra",
        "html_url": "https://github.com/agentultra",
        "followers_url": "https://api.github.com/users/agentultra/followers",
        "following_url": "https://api.github.com/users/agentultra/following{/other_user}",
        "gists_url": "https://api.github.com/users/agentultra/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/agentultra/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/agentultra/subscriptions",
        "organizations_url": "https://api.github.com/users/agentultra/orgs",
        "repos_url": "https://api.github.com/users/agentultra/repos",
        "events_url": "https://api.github.com/users/agentultra/events{/privacy}",
        "received_events_url": "https://api.github.com/users/agentultra/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [],
      "state": "closed",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 1,
      "created_at": "2015-02-06T20:47:12Z",
      "updated_at": "2015-02-06T22:19:48Z",
      "closed_at": "2015-02-06T21:00:43Z",
      "author_association": "OWNER",
      "pull_request": {
        "url": "https://api.github.com/repos/agentultra/dmon/pulls/7",
        "html_url": "https://github.com/agentultra/dmon/pull/7",
        "diff_url": "https://github.com/agentultra/dmon/pull/7.diff",
        "patch_url": "https://github.com/agentultra/dmon/pull/7.patch"
      },
      "body": "If the user has hy installed in sys.path then they can optionally define\ntheir stream modules in Hy.\n",
      "score": 1
    },
    {
      "url": "https://api.github.com/repos/akanda/akanda-rug/issues/210",
      "repository_url": "https://api.github.com/repos/akanda/akanda-rug",
      "labels_url": "https://api.github.com/repos/akanda/akanda-rug/issues/210/labels{/name}",
      "comments_url": "https://api.github.com/repos/akanda/akanda-rug/issues/210/comments",
      "events_url": "https://api.github.com/repos/akanda/akanda-rug/issues/210/events",
      "html_url": "https://github.com/akanda/akanda-rug/pull/210",
      "id": 55768229,
      "node_id": "MDExOlB1bGxSZXF1ZXN0MjgyMDA3NTk=",
      "number": 210,
      "title": "Fix test_execute_env_var_prepend",
      "user": {
        "login": "agentultra",
        "id": 120574,
        "node_id": "MDQ6VXNlcjEyMDU3NA==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/120574?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/agentultra",
        "html_url": "https://github.com/agentultra",
        "followers_url": "https://api.github.com/users/agentultra/followers",
        "following_url": "https://api.github.com/users/agentultra/following{/other_user}",
        "gists_url": "https://api.github.com/users/agentultra/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/agentultra/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/agentultra/subscriptions",
        "organizations_url": "https://api.github.com/users/agentultra/orgs",
        "repos_url": "https://api.github.com/users/agentultra/repos",
        "events_url": "https://api.github.com/users/agentultra/events{/privacy}",
        "received_events_url": "https://api.github.com/users/agentultra/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [],
      "state": "closed",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2015-01-28T15:14:12Z",
      "updated_at": "2015-02-06T19:09:39Z",
      "closed_at": "2015-01-28T15:47:43Z",
      "author_association": "CONTRIBUTOR",
      "pull_request": {
        "url": "https://api.github.com/repos/akanda/akanda-rug/pulls/210",
        "html_url": "https://github.com/akanda/akanda-rug/pull/210",
        "diff_url": "https://github.com/akanda/akanda-rug/pull/210.diff",
        "patch_url": "https://github.com/akanda/akanda-rug/pull/210.patch"
      },
      "body": "",
      "score": 1
    },
    {
      "url": "https://api.github.com/repos/akanda/akanda-rug/issues/209",
      "repository_url": "https://api.github.com/repos/akanda/akanda-rug",
      "labels_url": "https://api.github.com/repos/akanda/akanda-rug/issues/209/labels{/name}",
      "comments_url": "https://api.github.com/repos/akanda/akanda-rug/issues/209/comments",
      "events_url": "https://api.github.com/repos/akanda/akanda-rug/issues/209/events",
      "html_url": "https://github.com/akanda/akanda-rug/pull/209",
      "id": 55762556,
      "node_id": "MDExOlB1bGxSZXF1ZXN0MjgxOTcyMzI=",
      "number": 209,
      "title": "Add toggle for notifications.Publisher",
      "user": {
        "login": "agentultra",
        "id": 120574,
        "node_id": "MDQ6VXNlcjEyMDU3NA==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/120574?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/agentultra",
        "html_url": "https://github.com/agentultra",
        "followers_url": "https://api.github.com/users/agentultra/followers",
        "following_url": "https://api.github.com/users/agentultra/following{/other_user}",
        "gists_url": "https://api.github.com/users/agentultra/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/agentultra/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/agentultra/subscriptions",
        "organizations_url": "https://api.github.com/users/agentultra/orgs",
        "repos_url": "https://api.github.com/users/agentultra/repos",
        "events_url": "https://api.github.com/users/agentultra/events{/privacy}",
        "received_events_url": "https://api.github.com/users/agentultra/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2015-01-28T14:30:14Z",
      "updated_at": "2015-01-28T14:30:14Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "pull_request": {
        "url": "https://api.github.com/repos/akanda/akanda-rug/pulls/209",
        "html_url": "https://github.com/akanda/akanda-rug/pull/209",
        "diff_url": "https://github.com/akanda/akanda-rug/pull/209.diff",
        "patch_url": "https://github.com/akanda/akanda-rug/pull/209.patch"
      },
      "body": "This commit adds a configuration group named, \"ceilometer,\" and a boolean toggle to enable publishing notifications to the ceilometer queue. It defaults to \"False\" which makes the notifications.Publisher a no-op class since it is passed around to several areas of the code and none of which relies on return values of side-effects of calling methods on it.\n",
      "score": 1
    },
    {
      "url": "https://api.github.com/repos/akanda/akanda-rug/issues/208",
      "repository_url": "https://api.github.com/repos/akanda/akanda-rug",
      "labels_url": "https://api.github.com/repos/akanda/akanda-rug/issues/208/labels{/name}",
      "comments_url": "https://api.github.com/repos/akanda/akanda-rug/issues/208/comments",
      "events_url": "https://api.github.com/repos/akanda/akanda-rug/issues/208/events",
      "html_url": "https://github.com/akanda/akanda-rug/pull/208",
      "id": 55316043,
      "node_id": "MDExOlB1bGxSZXF1ZXN0Mjc5NDQ5Nzg=",
      "number": 208,
      "title": "Add option to enable ceilometer notifications",
      "user": {
        "login": "agentultra",
        "id": 120574,
        "node_id": "MDQ6VXNlcjEyMDU3NA==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/120574?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/agentultra",
        "html_url": "https://github.com/agentultra",
        "followers_url": "https://api.github.com/users/agentultra/followers",
        "following_url": "https://api.github.com/users/agentultra/following{/other_user}",
        "gists_url": "https://api.github.com/users/agentultra/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/agentultra/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/agentultra/subscriptions",
        "organizations_url": "https://api.github.com/users/agentultra/orgs",
        "repos_url": "https://api.github.com/users/agentultra/repos",
        "events_url": "https://api.github.com/users/agentultra/events{/privacy}",
        "received_events_url": "https://api.github.com/users/agentultra/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [],
      "state": "closed",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2015-01-23T18:37:53Z",
      "updated_at": "2015-01-26T18:12:07Z",
      "closed_at": "2015-01-23T18:46:19Z",
      "author_association": "CONTRIBUTOR",
      "pull_request": {
        "url": "https://api.github.com/repos/akanda/akanda-rug/pulls/208",
        "html_url": "https://github.com/akanda/akanda-rug/pull/208",
        "diff_url": "https://github.com/akanda/akanda-rug/pull/208.diff",
        "patch_url": "https://github.com/akanda/akanda-rug/pull/208.patch"
      },
      "body": "This change introduces a configuration group for ceilometer\nnotifications. The default for akanda is to not publish notifications.\n",
      "score": 1
    }
  ]
}